[package]
name = "monitor_server"
version = "0.1.0"
authors = ["various3211workd <kd1229568@st.kobedenshi.ac.jp>"]
edition = "2018"

[dependencies]
diesel = { version = "0.15.0", features = ["sqlite"] }
diesel_codegen = { version = "0.15.0", features = ["sqlite"] }
dotenv = "0.9.0"
